baseURL = 'https://example.org/'
languageCode = 'ja'
title = 'Clockwork'
theme = 'paper'

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'ai_9684_dct'               # twitter.com/YOUR_TWITTER_ID
  github = 'ai2playgame'                # github.com/YOUR_GITHUB_ID
  rss = true

  # home page profile
  avatar = 'hrkihepis@mozmail.com' # gravatar email or image url
  name = 'ai / イーアル'
  bio = '都内でゲームを作ったり本を読んだりしてます。'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
